<img src="./sharif.png" alt="SUT logo" width=300 height=300 align=left class="saturate">

<br>
<font>
<div dir=ltr align=center>
<font color=0F5298 size=7>
    Artificial Intelligence <br> <br>
<font color=2565AE size=5>
    CE Department <br>
    Fall 2024 - Prof. Rohban<br>
<font color=3C99D size=5>
    HW2 Practical <br>
    Constraint Satisfaction Problem<br>
<font color=696880 size=4>
    Shayan Shabani

____

## Personal Data

In [12]:
full_name = 'Ali Vakilzadeh'
student_number = '401102789'

## Sudoku Solver : Backtracking (25 Points)
Use your knowledge of the backtracking algorithm to solve the sudoku problem

### Importing Libraries

In [1]:

import pandas as pd
import numpy as np

### Preprocessing
Import the data and explore it!
The columns you need are named quizzes and solutions
Unsolved sudoku are in quizzes and solved ones are in solutions, use the solutions column to check whether you solve the sudoku correctly

In [2]:
# from google.colab import drive
# drive.mount('/content/drive')
# file_path = "/content/drive/My Drive/Ai_HW2/Practical 2/sudoku.csv"
file_path="sudoku.csv"
data = pd.read_csv(file_path)
display(data.head())

,Unnamed: 0,quizzes,solutions
0,0,0043002090050090010700600430060020871900074000...,8643712593258497619712658434361925871986574322...
1,1,0401000501070039605200080000000000170009068008...,3461792581875239645296483719658324174729168358...
2,2,6001203840084590720000060050002640300700800069...,6951273841384596727248369158512647392739815469...
3,3,4972000001004000050000160986203000403009000000...,4972583161864397252537164986293815473759641828...
4,4,0059103080094030600275001000300002010008200070...,4659123781894735623275681497386452919548216372...

In [3]:
# TODO: print info of the data
from IPython.display import display
display(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  2000 non-null   int64
 1   quizzes     2000 non-null   object
 2   solutions   2000 non-null   object
dtypes: int64(1), object(2)
memory usage: 47.0+ KB

None

In [4]:
# TODO: describe the data

display(data.describe())

print('***')

display(data['quizzes'].describe())

        Unnamed: 0
count  2000.000000
mean    999.500000
std     577.494589
min       0.000000
25%     499.750000
50%     999.500000
75%    1499.250000
max    1999.000000

***

count                                                  2000
unique                                                 2000
top       0043002090050090010700600430060020871900074000...
freq                                                      1
Name: quizzes, dtype: object

In [5]:
from ctypes import Array
def gridding_array(array):
    """
    TODO: turn the 1D array to a sudoku map
    """
    grid = [list(map(int, array[i:i+9])) for i in range(0, 81, 9)]
    return grid

In [6]:
#################################################
############### DO NOT CHANGE ###################
#################################################
def display_grid(grid):
    """
    This function prints a formatted representation of the 9x9 Sudoku grid with dividing lines.
    """
    separator_row = "+-----+-------+-----+"

    for row in range(9):
        if row % 3 == 0:
            print(separator_row)
        
        row_content = []
        for col in range(9):
            row_content.append(str(grid[row][col]))
            if (col + 1) % 3 == 0 and col != 8:
                row_content.append("|")
        
        print(" ".join(row_content))
        
    print(separator_row)
#################################################
#################################################
#################################################

### Backtracking Algorithm
Testing your algorithm on a sample sudoku is enough, but your code will be manually tested on multiple ones later

In [7]:
def is_empty(sudoku):
    """
    TODO: This function should check whether the sudoku is still empty (contains zero values)
    """
    for i in range(9):
        for j in range(9):
            if sudoku[i][j]==0:
                return True
    return False

In [8]:
def is_placement_valid(grid, num, position):
    """
    TODO: This function determines whether it's valid to place the number 'num' at the given 'position' on the Sudoku grid.
    """
    row, col = position
    #Check if the number is already in the row
    for i in range(9):
        if grid[row][i] == num:
            return False
    #Check if number is already in the col:
    for i in range(9):
        if grid[i][col] == num:
            return False

    #Check if number is already in the block:
    block_base_row = row-(row%3)
    block_base_col = col-(col%3)
    for i in range(3):
        for j in range(3):
            if grid[i + block_base_row][j + block_base_col] == num:
                return False
    return True

In [9]:
def get_an_empty_position(soduku):
  for i in range(9):
    for j in range(9):
      if soduku[i][j]==0:
        return (i,j)


def backtrack(sudoku):
    """
    TODO: implement the backtracking algorithm utilizing is_empty and is_valid functions
    """
    if not is_empty(sudoku):
        return True
    
    row,col=get_an_empty_position(sudoku)
    
    for i in range(1,10):
      if is_placement_valid(sudoku,i,(row,col)):

        sudoku[row][col]=i
        if backtrack(sudoku):
           return True
        sudoku[row][col]=0
    return False

In [15]:
def compare(sudoku, solution):
    """
    TODO: compare the sudoku you solved with its actual solution inside the dataset
        You have to subtract these two from each other and print the pretty version of the result
        which should contains only zeros
    """
    result = [[sudoku[i][j] - solution[i][j] for j in range(9)] for i in range(9)]
    display_grid(result)
    

for i in range(3):
    quiz = gridding_array(data.loc[i, 'quizzes'])
    solution = gridding_array(data.loc[i, 'solutions'])
    backtrack(quiz)
    compare(quiz, solution)
    print("")

+-----+-------+-----+
0 0 0 | 0 0 0 | 0 0 0
0 0 0 | 0 0 0 | 0 0 0
0 0 0 | 0 0 0 | 0 0 0
+-----+-------+-----+
0 0 0 | 0 0 0 | 0 0 0
0 0 0 | 0 0 0 | 0 0 0
0 0 0 | 0 0 0 | 0 0 0
+-----+-------+-----+
0 0 0 | 0 0 0 | 0 0 0
0 0 0 | 0 0 0 | 0 0 0
0 0 0 | 0 0 0 | 0 0 0
+-----+-------+-----+

+-----+-------+-----+
0 0 0 | 0 0 0 | 0 0 0
0 0 0 | 0 0 0 | 0 0 0
0 0 0 | 0 0 0 | 0 0 0
+-----+-------+-----+
0 0 0 | 0 0 0 | 0 0 0
0 0 0 | 0 0 0 | 0 0 0
0 0 0 | 0 0 0 | 0 0 0
+-----+-------+-----+
0 0 0 | 0 0 0 | 0 0 0
0 0 0 | 0 0 0 | 0 0 0
0 0 0 | 0 0 0 | 0 0 0
+-----+-------+-----+

+-----+-------+-----+
0 0 0 | 0 0 0 | 0 0 0
0 0 0 | 0 0 0 | 0 0 0
0 0 0 | 0 0 0 | 0 0 0
+-----+-------+-----+
0 0 0 | 0 0 0 | 0 0 0
0 0 0 | 0 0 0 | 0 0 0
0 0 0 | 0 0 0 | 0 0 0
+-----+-------+-----+
0 0 0 | 0 0 0 | 0 0 0
0 0 0 | 0 0 0 | 0 0 0
0 0 0 | 0 0 0 | 0 0 0
+-----+-------+-----+

## Sudoku Solver : CP-SAT Solver (15 Points)
Now we are going to explore ortools library and use it to solve the sudoku problem
Hint: use built-in functions of this library like AddAllDifferent and CpSolver; search for more ...
here is a useful link : https://developers.google.com/optimization/cp

In [11]:
from ortools.sat.python import cp_model
import pandas as pd
import numpy as np

In [ ]:

def solve_sudoku(sudoku):
    """
    Solves the given Sudoku puzzle using OR-Tools and returns the solved grid.

    :param sudoku: 2D numpy array representing the Sudoku puzzle (0 for empty cells)
    :return: Solved 2D numpy array or a message indicating failure
    """
    model = cp_model.CpModel()
    n = 9  # Standard Sudoku is 9x9

    # Create the variables for each cell in the Sudoku grid
    cells = [[model.NewIntVar(1, 9, f'cell_{i}_{j}') for j in range(n)] for i in range(n)]

    # Add constraints for rows, columns, and 3x3 subgrids
    for i in range(n):
        model.AddAllDifferent(cells[i])  # Row constraint
        model.AddAllDifferent([cells[j][i] for j in range(n)])  # Column constraint

    # 3x3 subgrid constraints
    for row in range(0, n, 3):
        for col in range(0, n, 3):
            model.AddAllDifferent([cells[row + i][col + j] for i in range(3) for j in range(3)])

    # Set the initial known values in the Sudoku puzzle
    for i in range(n):
        for j in range(n):
            if sudoku[i][j] != 0:
                model.Add(cells[i][j] == sudoku[i][j])

    # Solve the model
    solver = cp_model.CpSolver()
    status = solver.Solve(model)

    # Extract solution or return failure message
    if status == cp_model.FEASIBLE or status == cp_model.OPTIMAL:
        solved_grid = np.array([[solver.Value(cells[i][j]) for j in range(n)] for i in range(n)])
        return solved_grid
    else:
        return "No solution found for the given Sudoku puzzle."

In [16]:
"""
TODO: Test and print the pretty result of the above function, one sample sudoku from the dataset is enough
    use the compare function to make sure your answer is correct
"""
for i in range(7,10):
    quiz = gridding_array(data.loc[i, 'quizzes'])
    solution = gridding_array(data.loc[i, 'solutions'])
    solved = solve_sudoku(quiz)
    compare(solved, solution)
    print("")

+-----+-------+-----+
0 0 0 | 0 0 0 | 0 0 0
0 0 0 | 0 0 0 | 0 0 0
0 0 0 | 0 0 0 | 0 0 0
+-----+-------+-----+
0 0 0 | 0 0 0 | 0 0 0
0 0 0 | 0 0 0 | 0 0 0
0 0 0 | 0 0 0 | 0 0 0
+-----+-------+-----+
0 0 0 | 0 0 0 | 0 0 0
0 0 0 | 0 0 0 | 0 0 0
0 0 0 | 0 0 0 | 0 0 0
+-----+-------+-----+

+-----+-------+-----+
0 0 0 | 0 0 0 | 0 0 0
0 0 0 | 0 0 0 | 0 0 0
0 0 0 | 0 0 0 | 0 0 0
+-----+-------+-----+
0 0 0 | 0 0 0 | 0 0 0
0 0 0 | 0 0 0 | 0 0 0
0 0 0 | 0 0 0 | 0 0 0
+-----+-------+-----+
0 0 0 | 0 0 0 | 0 0 0
0 0 0 | 0 0 0 | 0 0 0
0 0 0 | 0 0 0 | 0 0 0
+-----+-------+-----+

+-----+-------+-----+
0 0 0 | 0 0 0 | 0 0 0
0 0 0 | 0 0 0 | 0 0 0
0 0 0 | 0 0 0 | 0 0 0
+-----+-------+-----+
0 0 0 | 0 0 0 | 0 0 0
0 0 0 | 0 0 0 | 0 0 0
0 0 0 | 0 0 0 | 0 0 0
+-----+-------+-----+
0 0 0 | 0 0 0 | 0 0 0
0 0 0 | 0 0 0 | 0 0 0
0 0 0 | 0 0 0 | 0 0 0
+-----+-------+-----+

## Graph Coloring
In this part, we are going to explore the graph coloring topic. Now we can use advanced options to speed up the process of constraint satisfaction

In [43]:
from itertools import combinations
from time import time
import numpy as np
import copy

### AC-3 Algorithm (20 Points)
First and foremost, implement the AC-3 algorithm to be later used in the problem

In [50]:
from collections import deque

def remove_inconsistent_values(node1, node2, csp):
  removed=False
  for x in csp['domains'][node1]:
    satisfied=False
    for y in csp['domains'][node2]:
      if(x,y) in csp['constraints'][(node1,node2)]:
        satisfied=True
        break
    if(not satisfied):
      csp['domains'][node1].remove(x)
      removed=True
  return removed


def AC3(csp, neighbors):
    """
    csp:
        dict{
            nodes: list of nodes,
            domains: dictionary {variable: [domain]},
            constraints: dictionary {(node_i, node_j): list of constraints}
        },
    neighbors:
        dict {var: [neighbor]}

    TODO: Implement the AC3 algorithm

    return: a bool to show whether the problem is consistent and if so, the reduced domain of the problem
    """
    #initialize queue
    queue=deque()
    for node1 in csp['nodes']:
      for node2 in neighbors[node1]:
        if(csp['constraints'][(node1, node2)]): #if 2 neighbors have constraints on eachother
          queue.append((node1, node2))

    while(queue):
      node1, node2=queue.popleft()
      if(remove_inconsistent_values(node1 , node2, csp)):
        for neighbor in neighbors[node1]:
          queue.append((neighbor, node1))

    consistency=True
    for node in csp['nodes']:
      if(len(csp['domains'][node])==0):
        return False, None
    return consistency, csp['domains']

### AC-4 Algorithm (20 Points)
Secondly, implement the AC-4 (Arc Consistency 4) algorithm. This algorithm enforces arc consistency by maintaining **support tables** and efficiently processing **a queue of arcs** for consistency checks. To help you implement it, here are the key steps and concepts to focus on:
1. **Support Tables**: For each pair of variable-value assignments, you must maintain a table that tracks the number of supporting values in the neighboring variables' domains. This table will allow you to quickly determine if a value is consistent with its neighbors
2. Start by initializing your support tables for all variable-value pairs. For each arc (X, Y), compute and store the number of values in Y's domain that support each value in X's domain based on the constraint between X and Y.
3. Initialize **a queue of arcs** with all pairs of variables that share a constraint
4. For each arc (X, Y) in the queue, check the support for each value in X's domain. If any value in X loses all supporting values in Y, remove that value from X’s domain.
5. If a value is removed from X’s domain, for every neighboring variable Z (other than Y), you must add the arc (Z, X) back into the queue for further consistency checks. This ensures that removing a value from X doesn’t create inconsistencies for other variables.
6. Whenever a value is removed from a domain, update the support tables for all neighboring variable-value pairs that depend on the removed value. This way, if a value of Z is only supported by the value that was removed from X, the support count for that value of Z should be decremented.
7. The algorithm terminates when the queue is empty, meaning all arcs have been processed and the domains of all variables are arc-consistent. If at any point a domain becomes empty, the problem is unsolvable.

In [49]:
def is_value_supported(csp, node , neighbor, value, neighbor_val):#based on constraints
  if((value, neighbor_val) in csp['constraints'][(node, neighbor)]):
    return True
  return False

def AC4(csp, neighbors):
    """
    csp:
        dict{
            nodes: list of nodes,
            domains: dictionary {variable: [domain]},
            constraints: dictionary {(node_i, node_j): list of constraints
        },

    TODO: Implement the AC4 algorithm

    return: a bool to show whether the problem is consistent and if so, the reduced domain of the problem
    """
    #initialize support tables
    support_dict={}#explicitly stores all values of a neighbor domain supporting a (var, val) pair
    support_table={}#storing the #of values of a neighbor domain supporting a (var, val) pair
    queue=deque()

    for node1 in csp['nodes']:
      for value in csp['domains'][node1]: #analyzing each (variable, value) pair:

        support_dict[(node1, value)]={}
        for neighbor in neighbors[node1]:#for all neighbors:

          support_dict[(node1, value)][neighbor]=[]
          support_table[(node1, value, neighbor)]=0

          for neighbor_val in csp['domains'][neighbor]:
            if(is_value_supported(csp, node1, neighbor, value, neighbor_val)):
              support_dict[(node1, value)][neighbor].append(neighbor_val)
              support_table[(node1, value, neighbor)]+=1
          if(support_table[(node1, value, neighbor)] ==0):
            queue.append((node1,value))

    while(queue):
      var, val =queue.popleft()
      csp['domains'][var].remove(val)
      if(not csp['domains'][var]):
        return False, None
      for neighbor in neighbors[var]:
        for neighbor_val in csp['domains'][neighbor]:
          if(val in support_dict[(neighbor, neighbor_val, var)]):
            support_table[(neighbor, neighbor_val, var)]-=1
            support_dict[(neighbor, neighbor_val, var)].remove(val)
            if(support_table[(neighbor, neighbor_val, var)]==0):
              queue.append(neighbor, neighbor_val)
    return True, csp['domains']

In [70]:
#################################################
############### DO NOT CHANGE ###################
#################################################

graph = {
    "WA": ["NT", "SA"],
    "NT": ["WA", "SA", "Q"],
    "SA": ["NT", "WA", "Q", "NSW", "V"],
    "Q": ["NT", "SA", "NSW"],
    "NSW": ["Q", "SA", "V"],
    "V": ["NSW", "SA"]
}

nodes = ["WA", "NT", "SA", "Q", "NSW", "V"]
domains = {}

for node in nodes:
    if node == "WA":
        domains[node] = ["R"]
    else:
        domains[node] = ["R", "G", "B"]

constraint = [(x, y) for x in ["R", "G", "B"] for y in ["R", "G", "B"] if x != y]
constraints = {}

for node in graph.keys():
    for neighbor in graph[node]:
        constraints[(node, neighbor)] = constraint
#################################################
#################################################
#################################################
#forming the csp:
csp = {
    'nodes': nodes,
    'domains': domains.copy(),
    'constraints': {(node, neighbor): constraint for node in graph for neighbor in graph[node]}
}
neighbors = {node: graph[node] for node in graph}


#Using AC_3:
start_time = time.perf_counter()
ac3_consistent, ac3_reduced_domains = AC3(csp, neighbors)
ac3_time = time.perf_counter() - start_time
if(ac3_consistent):
    print("AC-3 found a consistent solution:")
    print("AC3 Reduced Domains:", ac3_reduced_domains)
else:
    print("There wasnt consistent solution found when using AC-3")
print(f"AC-3 time consupmtion: {ac3_time:.5f} s\n")

# Using AC_4:
start_time = time.perf_counter()
ac4_consistent, ac4_reduced_domains = AC4(csp, neighbors)
ac4_time = time.perf_counter() - start_time
if(ac4_consistent):
    print("AC-4 found a consistent solution:")
    print("AC4 Reduced Domains:", ac4_reduced_domains)
else:
    print("There wasnt consistent solution found when using AC-3")
print(f"AC-4 time consupmtion: {ac4_time:.5f} s")

AC-3 found a consistent solution:
AC3 Reduced Domains: {'WA': ['R'], 'NT': ['G', 'B'], 'SA': ['G', 'B'], 'Q': ['R', 'G', 'B'], 'NSW': ['R', 'G', 'B'], 'V': ['R', 'G', 'B']}
AC-3 time consupmtion: 0.00011 s

AC-4 found a consistent solution:
AC4 Reduced Domains: {'WA': ['R'], 'NT': ['G', 'B'], 'SA': ['G', 'B'], 'Q': ['R', 'G', 'B'], 'NSW': ['R', 'G', 'B'], 'V': ['R', 'G', 'B']}
AC-4 time consupmtion: 0.00014 s

### Conclusion
Explain the differences between these two algorithms in terms of time and space complexity. Which one do you prefer to use?

**Your answer**: ...

## Backtracking + AC-3 and AC-4 algorithm (20 Points)
Now we are going to utilize the implemented algorithms to speed up the backtracking process, use both of the above algorithms, you must run ac3 and ac4 algorithms seperately.

In [75]:
def is_consistent(var, value, assignment, csp, neighbors):
    #checking consistency with already assigned neighbors
    for assigned in assignment:
        if assigned in neighbors[var]:#check if it is a neighbor
            # Check if there is consistency between var's value and assigned neighbor
            if (value, assignment[assigned]) not in csp['constraints'][(var, assigned)]:
                return False
    return True


def select_unassigned_variable(assignment, domains):
    # TODO: Select the unassigned variable with the smallest domain (MRV heuristic)
    unassigned_vars = [var for var in domains if var not in assignment]
    return min(unassigned_vars, key=lambda var: len(domains[var]))


def backtracking_search(csp, neighbors, ac3):
    if ac3:
        print("Using AC-3:")
        success, reduced_domains = AC3(csp, neighbors)
    else:
        print("Using AC-4:")
        success, reduced_domains = AC4(csp, neighbors)

    if(not success):
        print("Unsuccessful consistency check")
        return None

    csp['domains'] = reduced_domains
    return backtrack_on_reduced_domains(csp, neighbors, {})

def backtrack_on_reduced_domains(csp, neighbors, assignments):
    if (len(assignments) == len(csp['nodes'])):
        return assignments
    next_node=select_unassigned_variable(assignments, csp['domains'])
    for value in csp['domains'][next_node]:
        if(is_consistent(next_node, value, assignments, csp, neighbors)):
            assignments[next_node]=value
            result = backtrack_on_reduced_domains(csp, neighbors, assignments)#explore
            if(result):
                return result
            del assignments[next_node]#track back if couldnt finish
    return None

csp = {
    "nodes": nodes,
    "domains": domains,
    "constraints": constraints
}

# TODO: Solve using AC3 algorithm

print("\nBacktracking + AC3 algorithm: \n")
start = time.perf_counter()
solution = backtracking_search(csp, graph, True)
s = time.perf_counter() - start

if solution:
    print("Solution found:", solution)
else:
    print("No solution found!")

print("Solution retrieved in: %.4g seconds" % s)


# TODO: Solve using AC4 algorithm

print("\nBacktracking + AC4 algorithm:\n")
start = time.perf_counter()
solution = backtracking_search(csp, graph, False)
s = time.perf_counter() - start

if solution:
    print("Solution found:", solution)
else:
    print("No solution found!")

print("Solution retrieved in: %.4g seconds" % s)

Backtracking + AC3 algorithm:

Using AC-3:
Solution found: {'WA': 'R', 'NT': 'G', 'SA': 'B', 'Q': 'R', 'NSW': 'G', 'V': 'R'}
Solution retrieved in: 0.0001768 seconds

Backtracking + AC4 algorithm:

Using AC-4:
Solution found: {'WA': 'R', 'NT': 'G', 'SA': 'B', 'Q': 'R', 'NSW': 'G', 'V': 'R'}
Solution retrieved in: 0.0001871 seconds